title: KriWo 2019
license:
  full_form: GNU AFFERO GENERAL PUBLIC LICENSE V3.0
  short_form: GNU AGPL v3.0
organization: AStA TU Berlin
description: A website for KriWo 2019.
baseurl: ""  # the subpath of your site, e.g. /blog
url: ""  # the base hostname & protocol for your site
githuburl: "https://github.com/coala/projects"

gitter:
  gsoc:
    room: "https://gitter.im/coala/coala/gsoc"

gsoc_switch_month: 6

org:
  site_links:
    website: "https://asta.tu-berlin.de"
    twitter: "https://twitter.com/astatu"
    instagram: "https://www.instagram.com/astatuberlin"
    friendica: "https://friendica.astatu.berlin/profile/astatu"

twitter:
  username: astatu

plugins:
  - jekyll-netlify
  - jekyll-admin

# Build settings
exclude: [vendor, _projects/example.md]
markdown: kramdown
collections:
  projects:
    output: true
  reports:
    output: true
  faq:
    output: true

defaults:
  - scope:
      path: ''
      type: reports
    values:
      layout: report
      permalink: GSoC/:year/StatusReport/:title
